"""Gated self-development: write a spec for a *proposed* new skill.

Critically, this does NOT write Python code and does NOT load anything.
It drops a markdown spec under ``skills_proposed/`` (in the data volume,
not the source tree) and returns the path so the owner can review.

Code-generation then happens in a separate conversation with Kiro / your
editor of choice, where you can review the diff before it lands.
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

from pydantic import BaseModel, Field

from ...config import get_settings, load_policies
from ..base import Skill, SkillContext, SkillDenied, SkillError


_NAME_RE = re.compile(r"^[a-z][a-z0-9_.]{1,63}$")


class ProposeSkillInput(BaseModel):
    name: str = Field(
        ...,
        description="Proposed skill name, dotted snake_case e.g. 'bridge.sepolia_to_base'.",
    )
    family: str = Field(..., description="Kill-switch family, e.g. 'bridge'.")
    description: str = Field(..., min_length=10)
    inputs_schema: dict = Field(
        default_factory=dict,
        description="A JSON-schema-ish sketch of the Input model fields.",
    )
    outputs_schema: dict = Field(default_factory=dict)
    rationale: str = Field(..., description="Why this should exist; typical use.")
    pseudo_impl: str = Field(
        "", description="Optional pseudo-code or library notes for the implementer."
    )


class ProposeSkillOutput(BaseModel):
    path: str
    name: str


class ProposeSkillSkill(Skill):
    name = "system.propose_skill"
    family = "system"
    description = (
        "Draft a spec for a proposed new skill. Writes a markdown file to "
        "data/skills_proposed/ for the owner to review. Does NOT write "
        "executable code and does NOT add the skill to the registry."
    )
    Input = ProposeSkillInput
    Output = ProposeSkillOutput
    touches_filesystem = True

    async def run(self, inputs: ProposeSkillInput, ctx: SkillContext) -> ProposeSkillOutput:
        if not load_policies().self_dev.allow_propose_skill:
            raise SkillDenied("propose_skill disabled by policy")
        if not _NAME_RE.match(inputs.name):
            raise SkillError(f"invalid skill name: {inputs.name!r}")

        out_dir = get_settings().data_dir / "skills_proposed"
        out_dir.mkdir(parents=True, exist_ok=True)

        ts = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
        safe = inputs.name.replace(".", "_")
        path = out_dir / f"{ts}_{safe}.md"

        md = _render(inputs)
        path.write_text(md, encoding="utf-8")
        return ProposeSkillOutput(path=str(path), name=inputs.name)

    def summary(self, output: ProposeSkillOutput) -> str:
        return f"drafted spec for '{output.name}' at {output.path} (awaiting review)"


def _render(i: ProposeSkillInput) -> str:
    import json

    return (
        f"# Proposed skill: `{i.name}`\n\n"
        f"**Family:** `{i.family}`\n\n"
        f"## Description\n{i.description}\n\n"
        f"## Rationale\n{i.rationale}\n\n"
        f"## Inputs (sketch)\n```json\n{json.dumps(i.inputs_schema, indent=2)}\n```\n\n"
        f"## Outputs (sketch)\n```json\n{json.dumps(i.outputs_schema, indent=2)}\n```\n\n"
        f"## Pseudo-implementation notes\n{i.pseudo_impl or '_none_'}\n\n"
        f"---\n"
        f"_Auto-generated by the agent. Review, implement under "
        f"`src/agent/skills/{i.family}/...`, and commit when ready._\n"
    )
